language: go
sudo: false

matrix:
  include:
    - go: 1.5
    - go: 1.6
    - go: 1.7
    - go: 1.8
    - go: 1.9
    - go: "1.10"
    - go: tip
  allow_failures:
    - go: tip

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover

install:
  - if [[ $TRAVIS_GO_VERSION == 1.10* ]]; then go get github.com/golang/lint/golint; fi

script:
  - go get -t -v $(go list ./... | grep -v '/vendor/')
  - if [[ $TRAVIS_GO_VERSION == 1.10* ]]; then diff -u <(echo -n) <(gofmt -d .); fi
  - if [[ $TRAVIS_GO_VERSION == 1.10* ]]; then go vet $(go list ./... | grep -v '/vendor/'); fi
  - if [[ $TRAVIS_GO_VERSION == 1.10* ]]; then for package in $(go list ./... | grep -v '/vendor/'); do golint -set_exit_status $package; done; fi
  - go test -coverprofile=coverage.txt -covermode=atomic -v -race $(go list ./... | grep -v '/vendor/')


after_success:
  - bash <(curl -s https://codecov.io/bash)
